language: java
nafter_success:
- mvn deploy
before_install:
- openssl aes-256-cbc -K $encrypted_4f4ee75abb1a_key -iv $encrypted_4f4ee75abb1a_iv
  -in settings.xml.enc -out settings.xml -d
- mv settings.xml ~/.m2/settings.xml
notifications:
  email:
    - arena-uqbar@googlegroups.com

